@startuml
start
:get nessesary data;
note
configFilePath,
destination(s),
isDry,
cwd
end note
:getFile(configFilePath);
while (destinations)
:mergeConfig();
:createRsync();
:execute();
endwhile
stop
@enduml
